locales:
  en:
    name: Central Huasteca Nahuatl Keyboards
    description: >-
      Mobile OS keyboards for the Central Huasteca Nahuatl language from the
      Divvun group at UiT.
  nb:
    name: Central Huasteca Nahuatl tastatur
    description: Mobiltastatur for Central Huasteca Nahuatl fra Divvun-gruppa.
author: 'The Divvun Group, UiT Norgga 치rktala코 universitehta'
copyright: (c) 2017 Divvun/Giellatekno/UiT
email: feedback@divvun.no
organisation: UiT Norgga 치rktala코 universitehta
